# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest #windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'

- script: npm ci
  displayName: 'Install Playwright Deps'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: npx playwright test --project=$(browser) --grep=$(tagName)
  displayName: 'Start execution From GitRepo'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'playwright-report'
    artifact: 'Playwright HTML Report'
    publishLocation: 'pipeline'
  condition: always()

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/PlaywrightJunitReport.xml'
    testRunTitle: 'Junit Reporter'
  condition: always()